name: CI

on:
  - push
  - workflow_dispatch

jobs:
  ### Analyze Security Vulnerabilities
  security:
    name: Analyze Security Vulnerabilities
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew
      - name: Grant executable permission to Gradle
        run: chmod 777 /root/.gradle/wrapper/dists/gradle-5.6.4-all/ankdp27end7byghfw1q2sw75f/gradle-5.6.4/bin/gradle
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk11@master 
        # to make sure that SARIF upload gets called
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args:
            --sarif-file-output=snyk.sarif .
      - name: Upload result to workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          # tests and linter reports
          name: snyk.sarif
          path: snyk.sarif

