name: CI

on:
  - push
  - workflow_disptach

env:
    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  # Analyze Security Vulnerabilities
  security:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew
      - name: Install Snyk
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: run Snyk Open Source Test
        run: snyk test
        continue-on-error: true
      - name: run Snyk Code Test
        run: snyk code test
        continue-on-error: true

